name: Build and Push Docker image

on:
  pull_request:
    branches: [ main ]
    paths:
      - Dockerfile
      - .github/workflows/build-and-push.yml

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        tag:
          - main
          - v2025.3
          - v2025.4
          - v2025.5

    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ matrix.tag }}
          build-args: |
            TAG=${{ matrix.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
